

const puppeteer = require('puppeteer');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const config = require('../config/config');
const { db, queries, computeHash } = require('./database');

// Ensure reports directory exists
if (!fs.existsSync(config.paths.reports)) {
  fs.mkdirSync(config.paths.reports, { recursive: true });
}

/* ─────────────────────────────────────────────── */
/* HTML ESCAPE                                    */
/* ─────────────────────────────────────────────── */
function escapeHTML(str = '') {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/* ─────────────────────────────────────────────── */
/* BUILD HTML REPORT                               */
/* ─────────────────────────────────────────────── */
function buildReportHTML({ sessions, events, attacks, stats }) {
  const reportDate = new Date().toISOString();
  const reportHash = computeHash({ sessions, events, attacks, stats, reportDate });

  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Forensic Report</title>
<style>
body { font-family: Arial, sans-serif; font-size: 11px; color: #111 }
h1,h2 { color: #1f2937 }
table { width:100%; border-collapse: collapse; margin-top:10px }
th,td { border:1px solid #ddd; padding:6px }
th { background:#111827; color:#fff }
.badge { background:#2563eb; color:#fff; padding:2px 6px; border-radius:4px }
.sev-CRITICAL { color:#dc2626; font-weight:bold }
.sev-HIGH { color:#ea580c; font-weight:bold }
.sev-MEDIUM { color:#ca8a04 }
.sev-LOW { color:#16a34a }
.footer { margin-top:40px; font-size:9px; color:#6b7280 }
</style>
</head>

<body>

<h1>Anti-Honeypot Cyber Forensic Report</h1>
<p><b>Generated:</b> ${new Date(reportDate).toLocaleString()}</p>
<p><b>Integrity Hash (SHA-256):</b><br>${reportHash}</p>

<h2>Summary</h2>
<ul>
  <li>Total Sessions: ${sessions.length}</li>
  <li>Total Events: ${events.length}</li>
  <li>Attack Events: ${attacks.length}</li>
</ul>

<h2>Sessions</h2>
<table>
<tr>
  <th>IP</th><th>Country</th><th>Requests</th><th>Risk</th>
</tr>
${sessions.map(s => `
<tr>
  <td>${s.ip}</td>
  <td>${s.geo_country || 'Unknown'}</td>
  <td>${s.request_count}</td>
  <td class="sev-${s.risk_level}">${s.risk_level} (${s.risk_score})</td>
</tr>`).join('')}
</table>

<h2>Attack Events</h2>
<table>
<tr>
  <th>Time</th><th>IP</th><th>Type</th><th>Path</th><th>Severity</th>
</tr>
${attacks.map(a => `
<tr>
  <td>${new Date(a.timestamp).toLocaleString()}</td>
  <td>${a.ip}</td>
  <td><span class="badge">${a.attack_type}</span></td>
  <td>${escapeHTML(a.path)}</td>
  <td class="sev-${a.severity}">${a.severity}</td>
</tr>`).join('')}
</table>

<div class="footer">
CONFIDENTIAL — Generated by Anti-Honeypot Forensics System
</div>

</body>
</html>`;
}

/* ─────────────────────────────────────────────── */
/* GENERATE PDF                                    */
/* ─────────────────────────────────────────────── */
async function generateForensicReport(sessionId = null) {

  let sessions, events, attacks;

  if (sessionId) {
    const data = queries.getReportData(sessionId);
    sessions = data.session ? [data.session] : [];
    events = data.events || [];
    attacks = events.filter(e => e.attack_type);
  } else {
    sessions = queries.getSessions.all();
    events = queries.getRecentEvents.all();
    attacks = queries.getAttackEvents.all();
  }

  const stats = queries.getStats.get();
  const html = buildReportHTML({ sessions, events, attacks, stats });

  const filename = sessionId
    ? `forensic_${sessionId.slice(0,8)}_${Date.now()}.pdf`
    : `forensic_full_${Date.now()}.pdf`;

  const outputPath = path.join(config.paths.reports, filename);

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage'
      ],
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'load' });

    await page.pdf({
      path: outputPath,
      format: 'A4',
      printBackground: true,
      margin: { top: '20mm', bottom: '20mm' }
    });

    await browser.close();

    // ✅ ENSURE FILE EXISTS
    if (!fs.existsSync(outputPath)) {
      throw new Error('PDF was not written to disk');
    }

    return outputPath;

  } catch (err) {
    if (browser) await browser.close();
    throw err;
  }
}

module.exports = { generateForensicReport };